### ISSUE TITLE
Encountered the following issues while running the code

### ISSUE THREAD

**Issue by genesoul** [seominseok0429/Implicit-Stacked-Autoregressive-Model-for-Video-Prediction#6]
training is ok!
 
running  test  encountered the following issues 

Traceback (most recent call last):
  File "D:\VideoPrediction\ISAMVP\main.py", line 47, in <module>
    mse = exp.test(args)
  File "D:\VideoPrediction\ISAMVP\exp.py", line 189, in test
    pred_y = self.model(batch_x.to(self.device))
  File "C:\Users\VPE\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\VideoPrediction\ISAMVP\model.py", line 130, in forward
    time_emb = self.time_mlp(t)
  File "C:\Users\VPE\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\VideoPrediction\ISAMVP\model.py", line 30, in forward
    x = self.sinusoidaposemb(x)
  File "C:\Users\VPE\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\VideoPrediction\ISAMVP\model.py", line 13, in forward
    device = x.device
AttributeError: 'NoneType' object has no attribute 'device'

**Comment by Q-Chen-I** [comment]
Me too, Have you solved the problem?

**Comment by JLX690** [comment]
Me too

**Comment by AfrahKhader** [comment]
Same here, have anyone solve the problem?
